#nullable enable

using BepInEx;
using CruiserJumpPractice.Core.Ports;
using CruiserJumpPractice.Core.Validation;
using CruiserJumpPractice.Interop;
using CruiserJumpPractice.Interop.Game.Patches;

namespace CruiserJumpPractice;

/// <summary>
/// BepInEx plugin entrypoint for CruiserJumpPractice.
/// </summary>
/// <remarks>
/// MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Keep the
/// entrypoint metadata and startup log tied to that generated plugin identity.
/// </remarks>
[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
[BepInDependency("com.rune580.LethalCompanyInputUtils", BepInDependency.DependencyFlags.HardDependency)]
[BepInProcess("Lethal Company.exe")]
public class CruiserJumpPractice : BaseUnityPlugin
{
    private static PluginController? controller;

    /// <summary>
    /// Shared plugin controller used by game callback types constructed outside startup.
    /// </summary>
    internal static PluginController Controller => controller!;

    private void Awake()
    {
        var logger = new BepInExPluginLogger(base.Logger);

        var config = BepInExPluginConfig.Bind(Config);

        IValidationLogger validationLogger = config.ValidationLogging
            ? new BepInExValidationLogger(logger, System.DateTime.UtcNow)
            : DisabledValidationLogger.Instance;

        validationLogger.Record(
            ValidationLogRecord.PluginLoaded(
                version: MyPluginInfo.PLUGIN_VERSION,
                validationLogging: config.ValidationLogging
            )
        );

        // Create the workflow facade after BepInEx adapters are bound so Core
        // stays behind ports.
        controller = PluginController.Create(
            logger: logger,
            validationLogger: validationLogger
        );

        // Startup order matters: configure the guard after the controller is
        // wired and before patching so the first callback can be diagnosed.
        HarmonyCallbackGuard.Configure(
            new HarmonyCallbackDiagnosticReporter(
                logger: logger,
                validationLogger: validationLogger
            )
        );

        // Startup order matters: construct the controller before patching so the first game
        // callback can enter a fully wired plugin boundary.
        HarmonyPatchInstaller.Install();

        logger.LogInfo(
            $"Plugin {MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} is loaded!"
        );
    }
}
