// SPDX-License-Identifier: MIT
#nullable enable

using BepInEx;
using CruiserJumpPractice.Core.Ports;
using CruiserJumpPractice.Core.Validation;
using CruiserJumpPractice.Interop;
using CruiserJumpPractice.Interop.Game.Patches;

namespace CruiserJumpPractice;

// MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Keep the
// entrypoint metadata and startup log tied to that generated plugin identity.
[BepInPlugin(MyPluginInfo.PLUGIN_GUID, MyPluginInfo.PLUGIN_NAME, MyPluginInfo.PLUGIN_VERSION)]
[BepInDependency("com.rune580.LethalCompanyInputUtils", BepInDependency.DependencyFlags.HardDependency)]
[BepInProcess("Lethal Company.exe")]
public class CruiserJumpPractice : BaseUnityPlugin
{
    private static PluginController? controller;

    // Harmony and Netcode construct their callback objects outside our
    // construction path. This static entry exposes one plugin-level controller
    // instead of scattering use cases across patch and NetworkBehaviour classes.
    internal static PluginController Controller => controller!;

    private void Awake()
    {
        var logger = new BepInExPluginLogger(base.Logger);
        var validationLogging = Config.Bind(
            "Debug",
            "ValidationLogging",
            false,
            "Enable structured validation logs for release validation and troubleshooting."
        );
        IValidationLogger validationLogger = validationLogging.Value
            ? new BepInExValidationLogger(logger, System.DateTime.UtcNow)
            : DisabledValidationLogger.Instance;

        validationLogger.Record(
            "plugin_loaded",
            ValidationLogField.String("version", MyPluginInfo.PLUGIN_VERSION),
            ValidationLogField.Bool("validation_logging", validationLogging.Value)
        );

        // Inject the logger through the plugin logging port so Core and game interop can emit
        // diagnostics without depending on BepInEx logging types.
        controller = PluginController.Create(logger, validationLogger);

        // Startup order matters: construct the controller before patching so the first game
        // callback can enter a fully wired plugin boundary.
        HarmonyPatchInstaller.Install();

        logger.LogInfo($"Plugin {MyPluginInfo.PLUGIN_NAME} v{MyPluginInfo.PLUGIN_VERSION} is loaded!");
    }
}
