<!-- SPDX-License-Identifier: Unlicense -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- DLL name / Mod GUID -->
    <AssemblyName>com.aoirint.CruiserJumpPractice</AssemblyName>
    <!-- Mod name -->
    <Product>CruiserJumpPractice</Product>
    <RootNamespace>CruiserJumpPractice</RootNamespace>
    <!-- !!APP_VERSION_MARKER!! -->
    <Version>0.2.0-alpha.2</Version>
    <!-- Target framework. https://learn.microsoft.com/en-us/dotnet/standard/frameworks -->
    <TargetFramework>netstandard2.1</TargetFramework>
    <!-- C# language version.
         https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version -->
    <LangVersion>13.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <!-- Compile-only game dependencies -->
    <PackageReference Include="BepInEx.Core" Version="5.4.21" IncludeAssets="compile" />
    <PackageReference Include="LethalCompany.GameLibs.Steam" Version="81.0.5-ngd.0" IncludeAssets="compile">
      <Aliases>LethalCompany</Aliases>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="2022.3.62" IncludeAssets="compile">
      <Aliases>UnityEngine</Aliases>
    </PackageReference>
    <PackageReference Include="Rune580.Mods.LethalCompany.InputUtils" Version="0.7.13" IncludeAssets="compile">
      <Aliases>LethalCompanyInputUtils</Aliases>
    </PackageReference>

    <!-- Build/development-only dependencies -->
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" PrivateAssets="all" />
  </ItemGroup>
</Project>
