// SPDX-License-Identifier: Unlicense
#nullable enable

using HarmonyLib;

namespace CruiserJumpPractice.Interop.Game.Patches;

internal static class HarmonyPatchInstaller
{
    // MyPluginInfo is generated by BepInEx.PluginInfoProps at build time. Use it here so the
    // Harmony ID always matches the BepInEx plugin GUID declared by the entrypoint.
    private static readonly Harmony harmony = new(MyPluginInfo.PLUGIN_GUID);

    public static void Install()
    {
        // PatchAll(Assembly) makes Harmony scan that assembly for [HarmonyPatch] classes. Passing
        // this assembly explicitly keeps the scan target stable while this Interop type owns setup.
        harmony.PatchAll(typeof(HarmonyPatchInstaller).Assembly);
    }
}
